### ISSUE TITLE
Testing, CI Meta Issue

### ISSUE THREAD

**Issue by 0xAverageUser** [HumanbiOS/HumanBios-Server#13]
- [ ]  HumanbiOS/HumanBios-Telegram#47
- [ ] Add Jenkins 
- [ ] Unit tesing
- [ ] Fuzzer: Random walk through diagnosis graph 
- [ ] Load test for current hosting

Feel free to add items w.r.t. to reliability, stability, code style/climate here.

**Comment by penn5** [comment]
In terms of load testing, we first have to switch to async for the database, or we will totally fail load testing.
